
AllCops:
  Exclude:
   - 'main.rb'
   - 'test.rb'
  Metrics/LineLength:
  Max: 120

Style/Documentation:
  Exclude:
  - 'lib/trains/passenger_train.rb'
  - 'lib/trains/train.rb'
  - 'lib/trains/cargo_train.rb'
  - 'lib/carriages/cargo_carriage.rb'
  - 'lib/carriages/carriage.rb'
  - 'lib/instance_counter.rb'
  - 'lib/company_name.rb'
  - 'lib/station.rb'
  - 'lib/route.rb'
  - 'lib/carriages/passenger_carriage.rb'
  - 'lib/carriages/passenger_carriage.rb'

Metrics/MethodLength:
   Max: 20

Style/ClassVars:
  Exclude:
  - 'lib/trains/train.rb'
  - 'lib/station.rb'

Metrics/ClassLength:
  Max: 120
